# install numpy

In [2]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


# import numpy

In [3]:
import numpy as np #as np is an alias name

# check version of numpy

In [4]:
np.__version__

'1.24.3'

# creating numpy array

In [5]:
x=np.array([])

In [6]:
x

array([], dtype=float64)

type(x) #ndarray --n dimentional array

# creating an array

In [7]:
x=np.array([66,8,0,-3,5])

In [8]:
x

array([66,  8,  0, -3,  5])

In [9]:
type(x)

numpy.ndarray

In [10]:
len(x)

5

In [11]:
x.shape

(5,)

In [12]:
x.ndim #1 dimentional array

1

# indexing and slicing in 1D array

In [13]:
x=np.array([66,8,0,-3,5])

In [14]:
x

array([66,  8,  0, -3,  5])

In [15]:
x[2]

0

In [16]:
x[3]

-3

In [17]:
x[-1]

5

In [18]:
x[1:3]

array([8, 0])

In [19]:
x[-2:]

array([-3,  5])

In [20]:
x[3:5]

array([-3,  5])

# differences between python list and the numpy array
* numpy array are memory efficient than python list
* numpy array are faster than python list
* numpy array supports homogeneous data type and python list multiple data type

In [21]:
x=np.array([9,2,3], dtype=np.int8)

In [22]:
x

array([9, 2, 3], dtype=int8)

In [23]:
x=np.array([9,2,3],dtype=np.int16)

In [24]:
x

array([9, 2, 3], dtype=int16)

In [25]:
np.random.randint(1,10)#generates random integer between 1 and 10

9

In [26]:
np.random.randint(1,10)#generates random integer between 1 and 10

9

# numpy array are faster than python list

In [27]:
np.random.randint(1,10)#generates random integer between 1 and 10

6

In [30]:
np.random.seed(0) #seed generates same random number again and again
x=[np.random.randint(1,10)for i in range(50000)]
print(x)

[6, 1, 4, 4, 8, 4, 6, 3, 5, 8, 7, 9, 9, 2, 7, 8, 8, 9, 2, 6, 9, 5, 4, 1, 4, 6, 1, 3, 4, 9, 2, 4, 4, 4, 8, 1, 2, 1, 5, 8, 4, 3, 8, 3, 1, 1, 5, 6, 6, 7, 9, 5, 2, 5, 9, 2, 2, 8, 4, 7, 8, 3, 1, 4, 6, 5, 5, 7, 5, 5, 4, 5, 5, 9, 5, 4, 8, 6, 6, 1, 2, 6, 4, 1, 6, 1, 2, 3, 5, 3, 1, 4, 3, 1, 8, 6, 1, 3, 8, 3, 3, 4, 4, 3, 4, 5, 2, 3, 2, 5, 7, 9, 3, 4, 1, 1, 7, 1, 7, 4, 4, 9, 9, 9, 3, 4, 3, 1, 9, 9, 4, 9, 3, 9, 5, 4, 1, 5, 4, 7, 9, 1, 9, 6, 1, 7, 6, 4, 2, 9, 1, 5, 7, 6, 8, 9, 9, 3, 9, 7, 7, 2, 7, 9, 9, 4, 3, 4, 7, 4, 7, 6, 8, 1, 9, 5, 7, 6, 9, 3, 4, 8, 6, 4, 5, 6, 4, 4, 8, 8, 4, 3, 4, 8, 8, 6, 2, 3, 3, 9, 2, 6, 9, 5, 1, 3, 6, 6, 1, 9, 2, 2, 1, 4, 9, 9, 5, 5, 1, 4, 8, 4, 3, 2, 2, 3, 2, 5, 3, 6, 6, 6, 3, 6, 8, 8, 7, 2, 7, 8, 3, 4, 2, 6, 3, 1, 2, 1, 7, 1, 5, 9, 5, 4, 4, 9, 9, 8, 1, 4, 9, 8, 8, 2, 9, 5, 8, 1, 5, 1, 7, 5, 3, 5, 7, 4, 4, 8, 9, 6, 1, 9, 6, 5, 8, 5, 2, 4, 4, 3, 6, 3, 4, 6, 8, 3, 8, 2, 7, 6, 1, 1, 4, 2, 7, 7, 8, 9, 9, 8, 1, 9, 7, 9, 9, 4, 7, 2, 8, 5, 3, 1, 9, 3, 8, 9, 5, 5, 2, 8, 7, 5, 2, 

In [31]:
type(x)

list

In [32]:
%%time
sq=[item ** 2 for item in x]

CPU times: total: 31.2 ms
Wall time: 19.8 ms


In [34]:
x_array=np.array(x)

In [35]:
%%time
sq=x_array ** 2

CPU times: total: 0 ns
Wall time: 13.9 ms


# Numpy array supports homegeneous data tyte but python lists supports multiple data types

In [36]:
gift=['Iphone15', 'Rocket', 'Car', 'Plane', 'Macbook', 'Keyboard', 'Mouse', True]

In [37]:
gift

['Iphone15', 'Rocket', 'Car', 'Plane', 'Macbook', 'Keyboard', 'Mouse', True]

In [38]:
gift_array=np.array(gift)

In [39]:
gift_array

array(['Iphone15', 'Rocket', 'Car', 'Plane', 'Macbook', 'Keyboard',
       'Mouse', 'True'], dtype='<U8')

In [41]:
gift_array[-1]

'True'

In [42]:
type(gift_array[-1])

numpy.str_

In [43]:
np.array([5, 3.2, 8])

array([5. , 3.2, 8. ])

In [44]:
gift=['Flower', 'Book']
gift.append("teddy")

In [45]:
gift

['Flower', 'Book', 'teddy']

# data generation using numpy array

In [47]:
import numpy as np
gift_array=np.array(gift)
np.append(gift_array, 'Teddy')

array(['Flower', 'Book', 'teddy', 'Teddy'], dtype='<U6')

In [50]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [51]:
np.ones(5, dtype=np.int8)

array([1, 1, 1, 1, 1], dtype=int8)

In [52]:
np.zeros(10, dtype=np.float32)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [54]:
np.empty(10) # depends on state of memory

array([4.67296746e-307, 1.69121096e-306, 2.44773063e-307, 2.67018098e-306,
       1.42413555e-306, 1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
       1.42419530e-306, 0.00000000e+000])

# you can use np.arrange() which is equivelent to range() i python

In [55]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [57]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# .linespace()

In [62]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [63]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# .any() vs .all()

In [65]:
x=np.array([1,2,3,4,5,6,6,5,4,3,2,1])

In [66]:
x>=5

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False, False])

In [68]:
np.any(x>=5) #True if atleast one value is true on comparision

True

# I want to slice value which are true

In [70]:
x[x>=5]

array([5, 6, 6, 5])

In [72]:
x[x<=5]

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [73]:
x

array([1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1])

In [75]:
x>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
       False, False, False])

In [76]:
x<=5

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True])

In [77]:
x[x>=3 and x<=5] #numpy does not support logical opertor or bitwise operator

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [78]:
x[(x>=3) & (x<=5)]

array([3, 4, 5, 5, 4, 3])

# vector operation in numpy array

In [79]:
a=np.array([4,9])
b=np.array([2,3])

In [80]:
a+b #vector operations are added

array([ 6, 12])

In [81]:
x=[4,9]
y=[2,3]
x+y# concat list

[4, 9, 2, 3]

In [82]:
a-b

array([2, 6])

In [83]:
a**b

array([ 16, 729])

In [84]:
a//b

array([2, 3])

In [85]:
a/b

array([2., 3.])

# broadcasting in numpy array

In [86]:
x=np.array([2,5,10,25])

In [87]:
x*5

array([ 10,  25,  50, 125])

In [88]:
x+9

array([11, 14, 19, 34])

# array operations and statistics

In [89]:
x=np.array([1.5986,5.2318,6.63])

In [90]:
np.round(x,2)

array([1.6 , 5.23, 6.63])

In [91]:
np.floor(x)

array([1., 5., 6.])

In [92]:
np.ceil(x)

array([2., 6., 7.])

# converting 1D array to 2D array

In [93]:
x=np.array([7,8,6,5])

In [94]:
x

array([7, 8, 6, 5])

In [ ]:
x.ndi